title: SAMMI
tagline: SAMMI | Stream Automation, Management, Monitoring and Innovation | Works with Twitch, YouTube, OBS
description: Transform your ordinary stream into interactive experience for your viewers with SAMMI
name: SAMMI • Free Streamer Tool
stableVersion: 202244
url: "https://sammi.solutions"
author:
  twitter: SAMMISolutions
repository: https://github.com/SAMMISolutions/docs
logo: /assets/favicon/favicon-32x32.png
social:
  name: SAMMI
  links:
    - https://twitter.com/SAMMISolutions
    - https://github.com/SAMMISolutions
timezone: US/Pacific
google_analytics_id: G-Q3ZGBDKL0V
google_site_verification: XXX
twitter:
    username: SAMMISolutions
    card: summary
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-toc
  - jekyll-mentions
  - jekyll-relative-links
sass:
    style: compressed
relative_links:
  enabled:     true
  collections: true
kramdown:
  auto_ids: false
toc:
  min_level: 1
  max_level: 6
  ordered_list: false
  no_toc_section_class: no_toc_section
  list_id: toc
  list_class: section-nav
  sublist_class: ''
  item_class: "nav-link d-flex flex-row"
  item_prefix: toc-
defaults:
- scope:
    path: docs
    type: pages
  values:
    layout: post
- scope: 
    path: docs/commands
  values:
    menu: Commands
- scope: 
    path: docs/integrations
  values:
    menu: Integrations
- scope: 
    path: docs/local api
  values:
    menu: Local API      
- scope: 
    path: docs/faq
  values:
    menu: FAQ    
- scope: 
    path: docs/troubleshooting
  values:
    menu: Troubleshooting   
sass:
    sass_dir: _sass
algolia:
  application_id: 'I48YE43FLX'
  index_name: 'lioranboard'
collections_dir: doc_posts
collections:
  getting-started:
      output: true
  about:
      output: true
  components:
      output: true
  integrations:
      output: true
  integrations-obs:
      output: true
  integrations-twitch:
      output: true
  integrations-youtube:
      output: true
  triggers:
      output: true
  api-overview:
      output: true
  api-reference:
      output: true
  api-webhooks:
      output: true            
  faq-general: 
      output: true
  faq-receiver: 
      output: true   
  faq-commands: 
      output: true    
  troubleshooting-common:
      output: true  
  troubleshooting-errors:
      output: true  
  troubleshooting-bugs:
      output: true 
  troubleshooting-buttons:
      output: true 
  troubleshooting-outputs:
      output: true 
  commands-introduction: 
      output: true  
  commands-variable: 
      output: true 
  commands-number: 
      output: true 
  commands-string: 
      output: true
  commands-array: 
      output: true 
  commands-object: 
      output: true 
  commands-date-time: 
      output: true 
  commands-mouse-kb:
      output: true
  commands-statements: 
      output: true 
  commands-wait: 
      output: true 
  commands-trigger: 
      output: true       
  commands-file-general: 
      output: true
  commands-file-ini: 
      output: true
  commands-file-csv: 
      output: true
  commands-twitch: 
      output: true
  commands-youtube: 
      output: true
  commands-buffer: 
      output: true
  commands-sounds: 
      output: true
  commands-button: 
      output: true
  commands-misc: 
      output: true
  commands-obs-general: 
      output: true 
  commands-obs-filters: 
      output: true 
  commands-obs-media: 
      output: true 
  commands-obs-motion: 
      output: true 
  commands-obs-recording: 
      output: true 
  commands-obs-scenes: 
      output: true 
  commands-obs-sources: 
      output: true 
  commands-obs-streaming: 
      output: true 
  commands-obs-transitions: 
      output: true 
